baseurl = "https://www.shomedia.com/blog/bookshelf/"
title = "Sunish's Reading List 2016"
languageCode = "en-us"
theme = "hugo_theme_robust"

paginate = 10
paginatePath  ="page"

canonifyurls = true

[Params]
  Author = "Sunish Oturkar"
  categories = ["fiction", "non-fiction"]
